import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// 폴더 구조가 곧 사이드바. 순서는 각 문서 front matter의 sidebar_position과 _category_.json의 position으로 정한다.
// Components는 Common(도메인 무관 범용) → Broadcast(방송/채팅 전용) 순서.
const sidebars: SidebarsConfig = {
  main: [
    "intro",
    { type: "autogenerated", dirName: "foundations" },
    { type: "autogenerated", dirName: "components" },
    { type: "autogenerated", dirName: "api" },
  ],
};

export default sidebars;
